In [20]:
import sys

np.set_printoptions(threshold=sys.maxsize)
import urllib
import requests
import requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import multinomial
from typing import List
import seaborn as sns
from matplotlib.ticker import FormatStrFormatter
import random
from hmmlearn import hmm
from array import array

In [2]:
link = "https://www.ebi.ac.uk/ena/browser/api/fasta/CP009973.1?lineLimit=1000"
f = requests.get(link)


data = f.text

In [3]:
data

'>ENA|CP009973|CP009973.1 Yersinia pestis CO92, complete genome.\nGTAGCCGTCGGCACGAAAATGCCAGACTGGGTGCAGACAGGTTTTATCGAATATCTGCGC\nCGCTTTCCCAAAGATATGCCCTTCGAGCTGGCAGAAATACCTGCGGGTAAACGGGGCAAA\nAATGCCGATATCAAACGCATTCTGGAAAAAGAAGGCGAGCTGATGCTAGCTGCGGTAGGG\nAAAAATAACCGTATTGTCACGCTGGATATCCCAGGGACACCCTGGGAGACCCCGCAATTA\nGCCCAACAATTAGAACGTTGGAAGCAGGATGGCCGTGATGTAAGCCTGCTGATTGGCGGG\nCCGGAGGGGTTAGCCCCGGCCTGTAAAGCCGCCGCAGAGCAGAGTTGGTCGCTCTCTCCG\nTTAACGCTACCTCATCCTTTAGTGCGTGTTTTAGTGGCTGAAAGCCTCTATCGTGCCTGG\nAGTATTACGACCAATCATCCTTATCACCGGGAATAAACGGGCGATGAAACTGAATCAAGT\nGATGGCTCTGGCTCTGAGTAAGATGCTGGTTTTGAGCAAAATGACGTAAGCTGCGGAATG\nAAAAAAGAACCTAACCCTTTTCGCGACTATTCGGCTGAATCAGCCCTGTTTGTCCGCCGC\nGCCGTAGTGGCTTTTCTGGGTATCCTGCTACTGAGCGGGGTACTGGTTGCTAACCTCTAT\nAATTTGCAAATAATCCGTTTCGACGATTACAGCACCCGCTCCAACGACAACCGCATCAAA\nCTGGTTCCTATCGCCCCTAGCCGTGGCATGATATTTGACAGAAATGGCACACCACTGGCA\nTTAAACCGCACCATCTATCAATTAGAGTTGATGCCGGAAAAGATCGAAAACTTGTCAGCC\nACCCTCAATGCGCTGCGCCCAATAGTGGATCTGACTGACGACGATATCGCTAACTTTGAA\nAAAG

In [4]:
str = '>ENA|CP009973|CP009973.1 Yersinia pestis CO92, complete genome.\n'

In [5]:
data = data[64:len(data)]

In [6]:
data = data.replace('\n','')
data = data.replace('G','1')
data = data.replace('A','2')
data = data.replace('C','3')
data = data.replace('T','4')
data = data.replace(' ','' )

In [7]:
data

'142133143113231222241332123411141321232114444243122424341313313444333222124241333443121341132122242334131114222311113222224133124243222313244341122222122113121341241342134131142111222224223314244143231341124243332111232333411121233331322442133322322442122314411221321124113314124142213341341244113111331121111442133331133414222133133132121321214411431343434331442231342334324334442141314144442141134122213343424314133411214244231233224324334424323311122422231113124122234122432214124113434113434121422124134114444121322224123142213413112241222222122334223334444313123424431134122432133341444143313313133142141134444341114243341342341213111142341144134223343424224441322242243314443123124423213233313433223123223313243222341144334243133334213314113241242444123212224113232332341132442223313233243424322442121441241331122221243122223441432133233343224131341313332242141124341234123123124243134223444122222121313222313432314313444233434244133144222232331441233121141322143133314444132141224322443313443

In [9]:
data1 = []
for i in data:
    data1.append(int(i))

In [10]:
len(data1)

59940

In [54]:
model = hmm.CategoricalHMM(n_components=4, random_state = 0)

In [51]:
emissions = np.array(data1).reshape(-1, 1)
emissions

array([[1],
       [4],
       [2],
       [1],
       [3],
       [3],
       [1],
       [4],
       [3],
       [1],
       [1],
       [3],
       [2],
       [3],
       [1],
       [2],
       [2],
       [2],
       [2],
       [4],
       [1],
       [3],
       [3],
       [2],
       [1],
       [2],
       [3],
       [4],
       [1],
       [1],
       [1],
       [4],
       [1],
       [3],
       [2],
       [1],
       [2],
       [3],
       [2],
       [1],
       [1],
       [4],
       [4],
       [4],
       [4],
       [2],
       [4],
       [3],
       [1],
       [2],
       [2],
       [4],
       [2],
       [4],
       [3],
       [4],
       [1],
       [3],
       [1],
       [3],
       [3],
       [1],
       [3],
       [4],
       [4],
       [4],
       [3],
       [3],
       [3],
       [2],
       [2],
       [2],
       [1],
       [2],
       [4],
       [2],
       [4],
       [1],
       [3],
       [3],
       [3],
       [4],
       [4],
    

In [55]:
model.fit(emissions)

CategoricalHMM(n_components=4,
               random_state=RandomState(MT19937) at 0x23E2CBF1BA0)

In [56]:
hidden_states = model.predict(emissions)
hidden_states


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [40]:
trans_mat = model.transmat_
trans_mat

array([[5.83106514e-01, 2.55869346e-02, 3.22448707e-03, 3.88082064e-01],
       [1.21532050e-03, 3.13524828e-02, 4.33767543e-01, 5.33664653e-01],
       [5.27175614e-03, 9.93659087e-01, 1.03990622e-03, 2.92501378e-05],
       [2.50330556e-01, 7.04832921e-01, 2.60332872e-02, 1.88032358e-02]])

In [41]:
emission_prob=model.emissionprob_
emission_prob

array([[0.        , 0.03388064, 0.39507903, 0.17251072, 0.39852961],
       [0.        , 0.2693079 , 0.24925686, 0.28906618, 0.19236906],
       [0.        , 0.19688808, 0.17090331, 0.48353807, 0.14867053],
       [0.        , 0.35267164, 0.23299912, 0.08350036, 0.33082888]])

In [42]:
start_prob=model.startprob_
start_prob

array([1.62113895e-10, 8.91635608e-01, 2.38587930e-07, 1.08364153e-01])